# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Home\Documents\DANIIL\programming\python\Code\projekts\App-for-stakeholger-analys\interface\interface_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(861, 543)
        Dialog.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 823, 452))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"height: 25px;\n"
"weight: 50px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"height: 25px;\n"
"weight: 50px;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_3.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"height: 25px;\n"
"weight: 50px;")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_4.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"height: 25px;\n"
"weight: 50px;")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_5.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"height: 25px;\n"
"weight: 50px;")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_6 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_6.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"height: 25px;\n"
"weight: 50px;")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.comboBox_7 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_7.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"height: 25px;\n"
"weight: 50px;")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_8 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_8.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"height: 25px;\n"
"weight: 50px;")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setStyleSheet("background-color: rgb(71, 66, 66);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); \n"
"text-align: center;")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); ")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); ")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); ")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); ")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setStyleSheet("background-color: rgb(38, 34, 34);\n"
"font-size: 20px;\n"
"color: rgb(255, 255, 255); ")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(360, 490, 131, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(38, 34, 34);\n"
"    width: 75px;\n"
"    height: 50px;\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    text-align: center;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(43, 43, 43);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(79, 76, 76);\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Фамилия"))
        self.label_3.setText(_translate("Dialog", "Организация"))
        self.label_4.setText(_translate("Dialog", "Должность"))
        self.label_5.setText(_translate("Dialog", "Контактные данные"))
        self.label_6.setText(_translate("Dialog", "Каков уровень влияния стейкхолдера на рабочий процесс?"))
        self.comboBox.setItemText(0, _translate("Dialog", "..."))
        self.comboBox.setItemText(1, _translate("Dialog", "высокий"))
        self.comboBox.setItemText(2, _translate("Dialog", "средний"))
        self.comboBox.setItemText(3, _translate("Dialog", "низкий"))
        self.label_7.setText(_translate("Dialog", "Каков настрой стейкхолдера?"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "..."))
        self.comboBox_2.setItemText(1, _translate("Dialog", "вовлеченность"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "лояльность"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "нейтралитет"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "нелояльность"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "вредительство"))
        self.label_8.setText(_translate("Dialog", "Что важно и нужно этому стейкхолдеру?"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "..."))
        self.comboBox_3.setItemText(1, _translate("Dialog", "прибыль"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "паблисити"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "ничего"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "провал проекта"))
        self.label_9.setText(_translate("Dialog", "Каких конкретных результатов ожидает стейкхолдер?"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "..."))
        self.comboBox_4.setItemText(1, _translate("Dialog", "успех"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "никаких ожиданий"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "неудача"))
        self.label_10.setText(_translate("Dialog", "К какому кругу относится стейкхолдер?"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "..."))
        self.comboBox_5.setItemText(1, _translate("Dialog", "союзники"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "поддерживающие"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "нейтральные"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "неохотно участвующие"))
        self.comboBox_5.setItemText(5, _translate("Dialog", "оппоненты"))
        self.label_11.setText(_translate("Dialog", "Влияние проектного менеджера на стейкхолдера?"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "..."))
        self.comboBox_6.setItemText(1, _translate("Dialog", "высокий"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "средний"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "низкий"))
        self.label_12.setText(_translate("Dialog", "На сколько проблематичен стейкхолдер?"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "..."))
        self.comboBox_7.setItemText(1, _translate("Dialog", "безпроблемный"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "средне-проблематичный"))
        self.comboBox_7.setItemText(3, _translate("Dialog", "проблематичный"))
        self.label_13.setText(_translate("Dialog", "На каком уровне находится коммуникативность индивида?"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "..."))
        self.comboBox_8.setItemText(1, _translate("Dialog", "высокая"))
        self.comboBox_8.setItemText(2, _translate("Dialog", "средняя"))
        self.comboBox_8.setItemText(3, _translate("Dialog", "низкая"))
        self.label.setText(_translate("Dialog", "Имя"))
        self.pushButton.setText(_translate("Dialog", "Ок"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
